apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pricing-intelligence-api
  namespace: personalization-pricing
  labels:
    app.kubernetes.io/name: pricing-intelligence-api
    app.kubernetes.io/part-of: real-time-personalization-pricing-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pricing-intelligence-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
