apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-data-pvc
  namespace: personalization-pricing
  labels:
    app.kubernetes.io/part-of: real-time-personalization-pricing-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
